# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dave的小博客
brief-intro: Java and JavaScript Coder
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dave0824.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: #dave
facebook_username: #dave
github_username:  dave0824
email: dave_0824@163.com
weibo_username: 生活就像攀登。
zhihu_username: meng-xing-32-86
linkedIn_username: qq_41950229
dribbble_username:

description_footer: dave的小博客，记录生活的点滴

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #daveblog
disqus_shortname: dave

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxx";
# xxxxx字符串
baidu_tongji_id: 552aa8d99c04e57a157ba015b317ce20
google_analytics_id: UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6
port: 4001